# Generated by Django 4.1.2 on 2022-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0012_like_unique_together1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
