# Generated by Django 2.2 on 2022-10-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0013_user_kakao_id_alter_user_email_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
